/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.28
 * Generated at: 2018-03-30 14:16:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class configure_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


	String url = (String)request.getAttribute("URL");
	String app = (String)request.getAttribute("app");

      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<link href=\"/css/style.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<h1>Whoops!</h1>\n");
      out.write("\n");
      out.write("It doesn't look like you've configured SAML quite yet....please follow these steps:\n");
      out.write("\n");
      out.write("<ol>\n");
      out.write("\n");
      out.write("<h2><li>Go to your Salesforce org, and create a Connected App:</li></h2>\n");
      out.write("<p>Navigate to <b>Setup | Create | Apps</b></p>\n");
      out.write("<p>Scroll down to <b>Connected Apps</b> and click <b>New</b></p>\n");
      out.write("<p>Give your app a name, enter your email address and, optionally, set a logo, icon and description</p>\n");
      out.write("<p>Scroll down to Web App Settings and check the <b>Enable SAML</b> checkbox</p>\n");
      out.write("<p>Use the following <b>Start Url</b>: ");
      out.print( url );
      out.write(" </p>\n");
      out.write("<p>Use the following <b>Entity Id</b>: ");
      out.print( url );
      out.write(" </p>\n");
      out.write("<p>Use the following <b>ACS URL</b>: ");
      out.print( url );
      out.write(" </p>\n");
      out.write("<p>...and don't forget to authorize your Profile or Permission Set</p>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<h2><li>Now, configure SAML via a Metadata URL:</li></h2>\n");
      out.write("<p>Click 'Manage' from the Connected App detail page and copy your Metadata URL</p>\n");
      out.write("<p>Run this command using toolbelt:</p>\n");
      out.write("<pre>heroku config:set --app ");
      out.print( app );
      out.write(" SAML_METADATA=&lt;your metadata url&gt;</pre>\n");
      out.write("<p><a href=\"javascript:window.location.reload(true)\">Refresh this page</a></p>\n");
      out.write("\n");
      out.write("\n");
      out.write("<h2><li>Or...configured SAML via a Metadata File</li></h2>\n");
      out.write("<p>Click 'Manage' from the Connected App detail page and download your Connected App's SAML Metadata</p>\n");
      out.write("<p>Base64 Encode the Metadata</p>\n");
      out.write("<p>Run this command using toolbelt:</p>\n");
      out.write("<pre>heroku config:set --app ");
      out.print( app );
      out.write(" SAML_METADATA=&lt;your base64 encoded metadata&gt;</pre>\n");
      out.write("<p><a href=\"javascript:window.location.reload(true)\">Refresh this page</a></p>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
